let rand1 = Math.floor(Math.random() * 99) + 1;
let rand2 = Math.floor(Math.random() * 99) + 1;
let rand3 = Math.floor(Math.random() * 99) + 1;
let rand4 = Math.floor(Math.random() * 99) + 1;
let rand5 = Math.floor(Math.random() * 99) + 1;
console.log("random numbers is : " + rand1 + " " + rand2 + " " + rand3 + " " + rand4 + " " + rand5);
let sum = rand1 + rand2 + rand3 + rand4 + rand5;
let avg = (rand1 + rand2 + rand3 + rand4 + rand5) / 5;
console.log("sum 5random number is: " + sum);
console.log("avg 5random number is: " + avg);